[[preparacao]]
= Preparação

[quote, role=sidebar-quote]
____
Encontrar um local adequado.
____

O local, onde o Senhor Buddha praticava a meditação a andar depois de
atingir a Iluminação, em __Bodhgaya__, ainda existe nos dias de hoje. O
trajecto onde ele praticava esta forma de meditação tinha dezassete
passos de comprimento. Actualmente, os Monges da Floresta tendem a fazer
trajectos mais compridos. Podem ter até trinta passos. Os principiantes
podem achar esta distância um pouco longa, pois ainda não têm a
concentração desenvolvida. Quando chegam ao fim do trajecto, a mente
pode já ter dado a volta ao mundo e regressado. Lembrem-se que caminhar
é estimulante e que inicialmente a mente tende a dispersar-se.
Normalmente, é melhor os principiantes começarem com um trajecto mais
curto: quinze passos seria uma distância ideal.

Se praticarem meditação ao ar livre, tentem fazê-lo num local isolado
onde não se distraiam, nem sejam facilmente perturbados. É aconselhável
encontrarem um local para praticar que seja ligeiramente abrigado.
Poderá ser uma distracção caminhar numa zona aberta com paisagem, pois a
mente poderá ser atraída pelo cenário. Uma zona abrigada é especialmente
adequada para pessoas que têm tendência para pensar muito, ajudando-as a
acalmar a mente (Vsm, III, 103). Se praticarem num local fechado, a
mente tende a voltar-se para dentro, para o próprio ser, ao encontro da
paz.

[quote, role=sidebar-quote]
____
Preparar o corpo e a mente.
____

Quando tiverem escolhido o trajecto adequado, coloquem-se num dos
extremos do trajecto. Mantenham-se direitos. Coloquem à frente do vosso
corpo a mão esquerda e por cima dela a mão direita. Não andem com as
mãos atrás das costas. Lembro-me de um mestre de meditação, que quando
visitou o mosteiro e ao ver um dos visitantes a andar para trás e para a
frente com as mãos atrás das costas, fez o seguinte comentário: “Ele
não está a praticar meditação a andar, está a passear”. O mestre fez
esta observação porque reparou que não havia uma determinação clara de
focar a mente na meditação a andar, na qual se coloca as mãos à frente
do corpo para distinguir o que estamos a fazer de um simples passeio.

O objetivo primário da prática é desenvolver __samādhi__, e isto requer
esforço focalizado. A palavra em Pali, __samādhi__, significa focar a
mente, ou desenvolver a mente até esta se encontrar unificada através de
níveis graduais de atenção e concentração. Para focarmos a mente
necessitamos ser diligentes e determinados. Em primeiro lugar, é
necessário um certo grau de compostura física e mental. Começamos esta
compostura unindo as mãos à nossa frente, tranquilamente. Uma postura
calma do corpo ajuda a compor a mente. Assim, com o corpo tranquilo,
devem permanecer quietos e trazer a consciência e a atenção para o
corpo. Depois, levantem as mãos conjuntamente em __añjali__, um gesto de
respeito no qual une-se verticalmente as palmas das mãos em frente do
peito, e com os olhos fechados reflitam durante alguns minutos nas
qualidades do Buddha, do Dhamma e do Sangha (__Buddhanussati__,
_Dhammanussati_ e __Sanghanussati__).

Podem contemplar o facto de terem tomado refúgio no Buddha, aquele que é
Sábio, aquele que Vê e Conhece, o Desperto, o Iluminado. Reflictam por
alguns minutos, com o vosso coração, nas qualidades do Buddha. Depois
recordem-se do Dhamma – a Verdade que estão a tentar realizar e
desenvolver ao praticarem meditação a andar. Finalmente, tragam à mente
o Sangha – especialmente os Despertos, que realizaram a verdade
praticando meditação. Depois ponham as mãos em baixo à vossa frente e
determinem mentalmente durante quanto tempo irão praticar meditação a
andar, seja meia hora, uma hora ou mais. Independentemente do tempo que
determinaram para a prática, mantenham-no. Deste modo, nesta fase
inicial da meditação, estão a alimentar a mente com entusiasmo,
inspiração e confiança.

É importante lembrarem-se de olhar para o chão, cerca de um metro e meio
à vossa frente. Mantenham o olhar fixo, não se deixem distrair, seja o
que for que aconteça à vossa volta. Estejam conscientes do que sentem na
planta dos pés, e desenvolvendo assim uma atenção mais refinada e
sabendo claramente que estão a andar, enquanto andam.
