[[objectos]]
= Objectos

O Buddha mencionou quarenta objectos de meditação diferentes nos seus
ensinamentos (Vsm, III, 104), muitos dos quais podem ser utilizados na
meditação a andar. Contudo, uns são mais adequados que outros. Irei
examinar aqui alguns desses objectos de meditação, começando por aqueles
utilizados com mais frequência.

____
Consciência da postura
____

Neste método, enquanto caminhamos dirigimos toda a atenção para a planta
dos pés, reparando nas sensações conforme elas surgem e cessam (isto é,
presumindo que caminham descalços como faz a maioria dos monges, embora
se necessário possam usar sapatos com sola fina). Assim que começam a
andar, a sensação muda. Quando levantam e pousam o pé, pondo"-o em
contacto novamente com o solo, surge uma nova sensação. Estejam
conscientes desta sensação assim que ela surge na planta do pé. Quando o
pé se levanta de novo, tomem mentalmente nota da nova sensação, assim
que ela surge. Sempre que levantam e pousam cada pé, estejam conscientes
das sensações. A cada novo passo, novas sensações surgem e velhas
sensações cessam. Elas devem ser reconhecidas conscientemente. A cada
passo, novas sensações são experienciadas – uma sensação surge, uma
sensação cessa; uma sensação surge, uma sensação cessa.

Com este método, mantemos a consciência na sensação de andar, para cada
passo dado, para _vedanā_ (sensações agradáveis, desagradáveis ou
neutras). Estamos conscientes de qualquer tipo de _vedanā_ que surge na
planta dos pés. Quando estamos de pé, existe uma sensação de contacto
com o solo. Este contacto pode originar dor, calor ou outro tipo de
sensações. Dirigimos a nossa atenção consciente para estas sensações,
reconhecendo"-as. Quando levantamos um pé, a sensação muda assim que
perdemos o contacto com o solo. Quando baixamos o pé, assim que este
entra de novo em contacto com o solo, uma nova sensação surge. Enquanto
andamos, as sensações mudam constantemente, umas cessam e novas surgem.
Conscientemente, reparem no aparecimento e desaparecimento das sensações
na sola dos pés enquanto os levantam e pousam no chão. Assim toda a
atenção é dirigida apenas para as sensações que surgem enquanto
caminhamos.

Alguma vez repararam nas sensações que surgem nos pés enquanto caminham?
Acontecem sempre que andamos, mas normalmente não reparamos nestas
coisas subtis durante a nossa vida. Enquanto caminhamos a mente
normalmente encontra"-se noutro lugar qualquer. A meditação a andar é
uma forma de simplificar o que estamos a fazer enquanto o fazemos.
Trazemos a mente para o “aqui e agora”, e assim estamos conscientes de
estar a andar, enquanto andamos. Ao reconhecermos apenas as sensações
que surgem e cessam, a mente fica tranquila, tornando tudo mais simples.

A que velocidade se deve caminhar? Ajahn Chah recomendava que andássemos
naturalmente, nem muito depressa, nem muito devagar. Se caminharem muito
depressa, poderá ser difícil concentrarem"-se nas sensações que surgem e
cessam. Podem precisar de caminhar mais lentamente. Por outro lado, há
outras pessoas que podem precisar de caminhar mais depressa. Depende de
indivíduo para indivíduo. Encontrem o vosso próprio ritmo, aquele que
funcionar melhor, seja ele qual for. Podem começar com um ritmo lento e
irem aumentando gradualmente, até atingirem o ritmo normal de andamento.

Se a vossa concentração é fraca (isto é, se a mente dispersa“-se
facilmente), então andem muito devagar, até conseguirem estar no momento
presente a cada passo dado. Comecem por estabelecer a consciência, no
início do trajecto, e quando chegarem a meio do trajecto perguntem,
“Onde está a minha mente? Está consciente das sensações na planta dos
pés? Estou a notar o contacto aqui e agora, no momento presente?” Se a
mente estiver a vaguear, então tragam”-na de volta, reparando novamente
nas sensações na planta dos pés, e continuem a caminhar.

Quando chegarem ao fim do trajecto voltem“-se devagar e restabeleçam a
atenção novamente. Onde está a mente? Está a aperceber”-se das
sensações na planta dos pés? Ou vagueou? A mente tende a dispersar“-se
para outros lugares, indo atrás de pensamentos de ansiedade, medo,
felicidade, tristeza, preocupações, dúvidas, prazeres, frustrações e
muitos outros que possam surgir. Se não tiverem a atenção plenamente
estabelecida no objeto de meditação, restabeleçam”-na antes de
recomeçarem a andar. Restabeleçam a mente no simples acto de andar e
voltem para trás caminhando até ao fim do trajecto. Quando chegarem a
meio deverão reparar, “Agora estou a meio caminho” e confirmem
novamente para se certificarem que a mente está focada no objeto de
meditação. Depois, quando chegarem ao final do trajecto reparem
mentalmente, “Onde está a mente?" Desta forma, andam para trás e para a
frente, plenamente conscientes das sensações que vão surgindo e
cessando. Enquanto caminham, restabeleçam constantemente a concentração,
trazendo a mente de novo para o interior, retomando o estado consciente,
estando conscientes e reconhecendo as sensações a cada momento, assim
que surgem e cessam.

Enquanto estamos conscientes das sensações que sentimos na planta dos
pés, notamos que a mente se distrai menos, que não tem tanta tendência a
distrair"-se com as coisas que estão a acontecer à volta. Ficamos mais
calmos e a mente fica tranquila. Quando a mente fica calma e tranquila,
irão reparar que a postura de meditação a andar se torna numa actividade
demasiado agitada para uma mente com estas qualidades. Vão querer estar
quietos. Então parem e permitam à mente experienciar essa calma e
tranquilidade. Este estado é conhecido como __passaddhi__, que é um dos
factores da Iluminação.

Se enquanto andarem, a mente entrar num estado muito refinado, poderão
sentir que é impossível continuar. Para andar é necessário a vontade de
se moverem, e possivelmente a vossa mente encontra"-se demasiado focada
no objecto de meditação para continuar. Então parem de andar e pratiquem
meditação em pé. Meditação tem a ver com o trabalho da mente e não com
uma postura específica. A postura física utilizada é apenas uma forma de
potencializar o trabalho da mente.

Concentração e tranquilidade funcionam em conjunto com a consciência.
Juntamente com a energia, investigação do Dhamma, alegria e
equanimidade, estes são os “Sete Fatores da Iluminação." Quando
meditamos a mente está tranquila, e é devido a esta mesma tranquilidade
que surgem os estados de alegria, êxtase e beatitude. O Buddha disse que
a beatitude da paz é a felicidade suprema (MN, I, 454), e uma mente
concentrada experiencia essa paz. Esta paz pode ser experienciada nas
nossas vidas.

Tendo desenvolvido a prática da meditação a andar num contexto formal,
então quando estivermos a andar na nossa vida diária, a ir às compras, a
ir de um quarto para o outro, ou mesmo a andar até a casa de banho,
podemos praticar meditação a andar. Podemos estar conscientes de estar a
andar, simplesmente tendo isso presente. As nossas mentes podem estar
calmas e em paz. Esta é uma forma de desenvolvermos tranquilidade e
concentração nas nossas vidas diárias.

____
Da meditação sentada para a meditação a andar
____

Se a mente ficar tranquila com um determinado objecto de meditação
enquanto praticam meditação sentada, usem o mesmo objecto na meditação a
andar. Contudo, com alguns objectos de meditação subtis, tais como a
respiração, primeiro a mente deverá ter atingido um determinado grau de
estabilidade nesse estado de calma. Se a mente ainda não estiver calma e
começarem a meditação a andar focando"-se na respiração, vai ser
difícil, pois a respiração é um objeto muito subtil. Geralmente é melhor
começar com um objecto de meditação que seja facilmente reconhecido,
como as sensações que surgem na planta dos pés.

Para fazer a transição da meditação sentada para a meditação a andar, há
muitos objectos de meditação que podem ser utilizados, como por exemplo,
os quatro estados sublimes da mente: Bondade, Compaixão, Alegria
Empática e Equanimidade.

Enquanto caminharem para a frente e para trás, desenvolvam pensamentos
expansivos de bondade, “Possam todos os seres ser felizes, possam todos
os seres estar em paz, possam todos os seres estar livres de todo o
sofrimento”. Pode"-se usar a postura de meditação a andar como um
complemento da meditação sentada, desenvolvendo a meditação com o mesmo
objecto mas numa postura diferente.

____
Escolher um mantra
____

Se sentirem sonolência enquanto praticam meditação a andar, então devem
estimular a mente, em vez de a acalmarem, usem um mantra para que ela
fique mais focada e desperta. Usem um mantra como __Buddho__, repetindo
contínua e silenciosamente a palavra para vós mesmos. Se a mente
continuar a vaguear, então comecem a dizer _Buddho_ rapidamente e andem
para trás e para a frente depressa. Enquanto andam, recitem a palavra
__Buddho__, __Buddho__, __Buddho__. Desta forma a mente poderá focar"-se
rapidamente.

Quando Tan Ajahn Mun, um famoso mestre de meditação da Tradição da
Floresta, esteve no norte da Tailândia, com as tribos das montanhas,
eles não sabiam nada acerca de meditação ou de monges que meditavam.
Contudo, as pessoas dessas tribos são muito curiosas. Quando o viram a
caminhar para trás e para a frente, percorrendo o seu trajeto,
seguiram"-no em fila. Quando ele chegou ao fim do trajeto e se voltou,
toda a tribo estava ali de pé!

Repararam que Ajahn Mun estava a andar para trás e para a frente com os
olhos postos no chão e presumiram que andava à procura de alguma coisa.
Perguntaram, “O que anda à procura Venerável Senhor? Podemos ajudá“-lo
a encontrar?” Tan Ajahn Mun respondeu astutamente, “Estou à procura de
__Buddho__, o Buddha no coração. Vocês podem ajudar“-me a encontrá”-lo
andando para trás e para a frente, fazendo os vossos próprios trajetos,
procurando o Buddha." E com esta instrução simples e bonita muitos deles
começaram a meditar, e Tan Ajahn Mun disse que obtiveram excelentes
resultados.

____
Contemplar as coisas como elas são
____

Investigar o Dhamma (__Dhammavicaya__) é um dos factores de Iluminação,
e é um tipo de contemplação acerca dos ensinamentos e das leis da
natureza que pode ser utilizado quando andamos para trás e para a
frente, no caminho de meditação a andar. Isto não significa que
estejamos apenas a especular ou a pensar sobre qualquer coisa antiga.
Pelo contrário, é uma reflexão e contemplação constante sobre a Verdade
(Dhamma).

Investigar a impermanência: podemos, por exemplo, contemplar a
impermanência observando o processo de mudança e perceber que todas as
coisas estão sujeitas à mudança. Desenvolvemos uma percepção clara do
surgir e do cessar de toda a experiência. “A Vida” é um processo
contínuo de surgimento e cessação e toda a experiência condicionada está
sujeita a esta lei da natureza. Contemplando esta Verdade compreendemos
as características da existência. Vemos que todas as coisas estão
sujeitas à mudança. Todas as coisas são insatisfatórias. Todas as coisas
são impessoais. Podemos investigar estas características fundamentais da
natureza na prática da meditação a andar.

____
Relembrando a generosidade e a virtude
____

O Buddha insistiu continuamente na importância da generosidade (It, 26)
e da virtude (SN, V, 354). Enquanto praticamos meditação a andar,
podemos reflectir sobre a nossa virtude ou atos de generosidade.
Caminhando para trás e para a frente, perguntem"-se, “Que actos de
bondade fiz hoje?"

Um mestre de meditação com o qual pratiquei, comentava frequentemente
que uma das razões porque os meditadores não conseguiam estar em paz é o
facto de durante o dia não terem praticado suficientemente a bondade. A
bondade é uma almofada de tranquilidade, uma base para termos paz. Se a
praticarmos durante o dia – termos dito uma palavra amável, termos feito
uma boa acção, termos sido generosos ou termos tido compaixão – então a
mente experienciará alegria e êxtase. Estes actos de bondade e a
felicidade daí resultante são as condições que determinarão a
concentração e a paz. O poder da bondade e da generosidade conduz à
felicidade, e esta felicidade saudável é a fundação da concentração e da
sabedoria.

Quando a mente está inquieta, agitada, com raiva ou frustrada,
recordarmos as nossas boas acções é um objecto de meditação apropriado.
Se a mente não está em paz, então lembrem"-se das vossas acções
bondosas. O objectivo não é alimentar o ego, mas reconhecer o poder da
bondade e da moralidade. Actos de bondade, virtude e generosidade trazem
alegria à mente, e a alegria é um factor de Iluminação (SN, V, 68).

Relembrar actos de generosidade, reflectir nos benefícios de dar,
recordar a vossa virtude, contemplar a pureza da não"-violência, a
pureza da honestidade, a pureza de relações sexuais correctas, a pureza
da veracidade, a pureza da mente sem confusão quando se evitam
intoxicantes; quando praticamos meditação a andar todas estas memórias
podem servir de objecto de meditação.

____
Relembrando a natureza do corpo
____

Podemos também meditar sobre a morte ou na natureza não atraente do
corpo, a partir das contemplações _Asubha_ – de cadáveres em diversos
estados de decomposição. Podemos visualizar este corpo separado em
partes, tal como um estudante de medicina disseca um corpo.
“Descascamos” a pele e “vemos” o que está por baixo, as camadas de
carne, os tendões, os ossos, os órgãos. Podemos mentalmente remover cada
um dos órgãos do corpo para que possa ser investigado e compreendido. De
que é feito o corpo? Que partes o compõem? Isto sou eu? Isto é
permanente? É digno de ser chamado eu?

O corpo é apenas um aspecto da natureza, como uma árvore ou uma nuvem –
não é diferente. O problema fundamental é a nossa identificação com ele:
quando a mente se apega à ideia de que este corpo é o meu corpo, quando
se deleita com este corpo e quando se deleita com outros corpos; quando
pensa ’ Isto sou eu. Isto sou eu próprio. Isto pertence"-me’.

Podemos desafiar esta identificação com o corpo através da contemplação
e da investigação. Tomamos como objecto os ossos deste corpo. Quando
praticarmos meditação a andar, visualizamos um osso e compreendemos a
sua substância, vendo“-o fragmentar”-se e voltar ao elemento terra. O
osso é formado por cálcio que é absorvido pelo corpo através do consumo
de vegetais e de matéria animal. Ele vem da terra. Os químicos
juntam"-se para formar o osso, e eventualmente esse osso voltará à
terra.

Cálcio é apenas cálcio, não tem a qualidade de ser o meu cálcio ou o de
outra pessoa qualquer. Terra apenas volta para a terra, cada elemento
volta à sua forma natural. “Isto não sou eu, isto não é meu, isto não é
digno de ser chamado eu”. Meditamos sobre os ossos decompondo“-os nos
seus elementos e devolvendo”-os à terra. Voltamos a fazê“-lo
novamente, decompondo”-os e devolvendo"-os. Continuamos este processo
mental até que surja uma compreensão clara.

Se estiverem a meditar no corpo e ainda não tiverem decomposto
totalmente o objecto de meditação nos quatro elementos (terra, ar, fogo
e água) e o reconstituírem novamente, então o trabalho da meditação
ainda não está concluído. O trabalho não está feito. Continuem.
Continuem a andar. Andem para trás e para a frente até estarem aptos a
estabelecer a percepção mental de ver _asubha_ no __subha__, ou seja,
verem a não“-beleza, a falta de encanto e o não atraente no que à
partida assumimos como belo, encantador e atraente. Com o objectivo de o
vermos como realmente é, decompomos este corpo e devolvemo”-lo aos seus
elementos naturais.

O treino da mente na investigação da natureza conduz à sabedoria. Ao
repetir o exercício de decompor o corpo nos seus quatro elementos –
terra, ar, fogo e água – a mente vê e compreende que este corpo não sou
eu, não é meu, não sou eu próprio. Ela vê que os quatro elementos que
constituem o corpo são apenas aspectos da natureza. É a mente que se
apega à ideia de que este corpo sou eu próprio. Então, desafiamos esse
apego; não o aceitamos cegamente, pois é esse apego que nos causa todo o
sofrimento.

____
Outras contemplações
____

Outro objecto de meditação que o Buddha recomendou é a reflexão sobre a
paz e a sua natureza (Vsm, 197). Ainda outro é ponderar sobre as
qualidades da Iluminação. Alternativamente, podemos andar para trás e
para a frente reflectindo nas qualidades do Buddha, nas qualidades do
Dhamma ou nas qualidades do Sangha. Ou podemos trazer à memória seres
divinos (__devas__) e as qualidades necessárias para nos tornarmos um
ser divino (Vsm, III, 105).

____
Utilizar a contemplação sabiamente
____

No repertório da meditação budista há imensos objectos de meditação. O
vosso objecto de meditação deve ser escolhido cuidadosamente. Selecionem
um que estimule a mente quando esta necessita ser estimulada, ou que a
pacifique quando ela necessite de ser acalmada. No entanto, quando
utilizamos estas contemplações na prática de meditação é necessária
alguma prudência para que a mente não entre em pensamentos
especulativos, divagando. Isto é muito fácil de acontecer. Temos que
estar muito atentos e repararmos no início, no meio e no final do
trajecto: “Tenho realmente o meu objecto de meditação presente ou estou
a pensar noutra coisa qualquer?" Se estiver a andar para trás e para a
frente, no trajecto de meditação, durante quatro horas, mas se estiver
atento e consciente do que está a fazer apenas durante um minuto dessas
quatro horas, terei praticado apenas um minuto de meditação.

Lembrem"-se de que não é a quantidade de horas de meditação que
interessa, mas sim a qualidade. Se a vossa mente estiver a vaguear por
outro lado qualquer enquanto anda, então não estão a meditar. Não estão
a meditar no sentido em que o Buddha usou a palavra meditação, como
_Bhāvanā_ ou desenvolvimento mental (AN. III. 125-127). O mais
importante não é a quantidade de horas que cada um medita, mas sim a
qualidade da mente.
