[[conclusao]]
= Conclusão

Ao longo da História do Budismo, muitos monges e monjas atingiram
compreensão, sabedoria e Iluminação enquanto praticavam meditação a
andar, investigando a Verdade. Na Tradição Monástica da Floresta todos
os aspectos das nossas vidas são considerados uma oportunidade de
meditação. Meditação não é apenas quando estamos sentados nas nossas
almofadas de meditação. Todos os processos da vida são oportunidade para
investigar a realidade. Empenhamo-nos em ver as coisas como elas são,
perceber que surgem e cessam, de modo a compreender a realidade tal como
ela é.

Espero que esta palestra sobre meditação a andar, tenha acrescentado
algo ao vosso repertório de técnicas de meditação. Meditação a andar é
algo que podem utilizar na vida diária, quando estão ativos e também
quando praticam meditação formal. A meditação a andar pode ser outra
forma de desenvolver a mente. A meditação a andar oferece trabalho à
mente. Se tiverem problemas com sonolência, não se sentem, deixando-se
estar simplesmente, levantem-se e ponham a mente a trabalhar. Isto é
_kammatthāna_ – o trabalho fundamental da mente.

Na Tradição da Floresta sempre que um mestre de meditação vai a um
mosteiro, um dos locais que ele observa são os espaços onde os monges
praticam meditação a andar, para verificar as pegadas aí existentes. Se
o chão dos trajectos de meditação a andar estiver muito usado, é sinal
de ser um bom mosteiro.

_Possa o seu caminho de meditação ser bem usado._
